/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javatodoapp.Interface;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFormattedTextField;

/**
 *
 * @author sebastian
 */
public class JavaToDoAppGui extends javax.swing.JFrame {

    /**
     * interface to database
     */
    private Interface connector;

    /**
     * Creates new form JavaToDoAppGui
     */
    public JavaToDoAppGui() {
        initComponents();
        jPasswordField1UserPass.enableInputMethods(true);
        connector = new Interface();
        connector.setDbControler(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jDialog1TaskModyf = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTextField1TitleTask = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1DescriptionTask = new javax.swing.JTextArea();
        jFormattedTextDateTaskBegin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1DayTaskEnd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1AllDay = new javax.swing.JCheckBox();
        jButton2CommitAddtask = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2TimeEnd = new javax.swing.JTextField();
        jTextField3TimeStart = new javax.swing.JTextField();
        jTextField4Status = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1User = new javax.swing.JTextField();
        jLabel1TextLogin = new javax.swing.JLabel();
        jLabel2TextPass = new javax.swing.JLabel();
        jPasswordField1UserPass = new javax.swing.JPasswordField();
        jButton1Login = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1TaskViews = new javax.swing.JTable();
        jButton2AddTask = new javax.swing.JButton();
        jLabel1Msg = new javax.swing.JLabel();
        jLabel1MsgContent = new javax.swing.JLabel();
        jButton2Logout = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jTextArea1DescriptionTask.setColumns(20);
        jTextArea1DescriptionTask.setRows(5);
        jScrollPane2.setViewportView(jTextArea1DescriptionTask);

        jLabel1.setText("Data rozpoczecia");

        jLabel2.setText("Data akończenia");

        jLabel3.setText("Czy cały dzień");

        jButton2CommitAddtask.setText("Dodaj zadanie");
        jButton2CommitAddtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CommitAddtaskActionPerformed(evt);
            }
        });

        jLabel4.setText("Start");

        jLabel5.setText("Koniec");

        jTextField4Status.setText("nowe");

        jLabel6.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jTextField1TitleTask)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField4Status, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2CommitAddtask)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox1AllDay)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1DayTaskEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2TimeEnd))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFormattedTextDateTaskBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(23, 23, 23)
                                        .addComponent(jTextField3TimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(74, 74, 74)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1TitleTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextDateTaskBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3TimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1DayTaskEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2TimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jCheckBox1AllDay))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2CommitAddtask)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jDialog1TaskModyfLayout = new javax.swing.GroupLayout(jDialog1TaskModyf.getContentPane());
        jDialog1TaskModyf.getContentPane().setLayout(jDialog1TaskModyfLayout);
        jDialog1TaskModyfLayout.setHorizontalGroup(
            jDialog1TaskModyfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1TaskModyfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1TaskModyfLayout.setVerticalGroup(
            jDialog1TaskModyfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1TaskModyfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1TextLogin.setText("Login");

        jLabel2TextPass.setText("Hasło");

        jPasswordField1UserPass.setText("jPasswordField1");

        jButton1Login.setText("Logowanie");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });

        jTable1TaskViews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1TaskViews);

        jButton2AddTask.setText("Dodaj");
        jButton2AddTask.setEnabled(false);
        jButton2AddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AddTaskActionPerformed(evt);
            }
        });

        jLabel1Msg.setText("Komunikaty :");

        jButton2Logout.setText("Wyloguj");
        jButton2Logout.setEnabled(false);
        jButton2Logout.setFocusPainted(false);
        jButton2Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel1TextLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1User, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2TextPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1UserPass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1Msg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1MsgContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2AddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1TextLogin)
                    .addComponent(jLabel2TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1UserPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2Logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2AddTask)
                    .addComponent(jLabel1Msg)
                    .addComponent(jLabel1MsgContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
        // TODO add your handling code here:
        if (connector.login(jTextField1User.getText(), jPasswordField1UserPass.getPassword())) {
            jLabel1MsgContent.setText("udane logowanie!");

            jButton1Login.setEnabled(false);
            jTextField1User.setEnabled(false);
            jPasswordField1UserPass.setEnabled(false);
            jButton2Logout.setEnabled(true);
            jButton2AddTask.setEnabled(true);

            connector.updateTable(jTable1TaskViews, "tasks");

        } else {
            jLabel1MsgContent.setText("błędne logowanie!");
        }

    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jButton2LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LogoutActionPerformed
        // TODO add your handling code here:
        if (connector.logout()) {
            jLabel1MsgContent.setText("wylogowano z aplikacji!");

            jButton1Login.setEnabled(true);
            jTextField1User.setEnabled(true);
            jPasswordField1UserPass.setEnabled(true);
            jButton2Logout.setEnabled(false);
            jButton2AddTask.setEnabled(false);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1TaskViews.getModel();
            tableModel.getDataVector().removeAllElements();
            tableModel.fireTableDataChanged(); // notifies the JTable that the model has changed
        }
    }//GEN-LAST:event_jButton2LogoutActionPerformed

    private void jButton2AddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AddTaskActionPerformed
        // TODO add your handling code here:
        System.out.println("Dodaj zadanie");

        Date date = (Date) jFormattedTextDateTaskBegin.getValue();
        jFormattedTextDateTaskBegin = new JFormattedTextField(new SimpleDateFormat("yyyy-MM-dd"));
        jFormattedTextDateTaskBegin.setValue(date);
        jDialog1TaskModyf.setSize(jDialog1TaskModyf.getPreferredSize());
         System.out.println("wielkosc"+jDialog1TaskModyf.getPreferredSize());
        jDialog1TaskModyf.setVisible(true);


    }//GEN-LAST:event_jButton2AddTaskActionPerformed

    private void jButton2CommitAddtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CommitAddtaskActionPerformed
        // TODO add your handling code here:
         System.out.println("Dodaj zadanie - clik!\n");
         System.out.println(jTextField1TitleTask.getText()+"\n");
         System.out.println(jTextArea1DescriptionTask.getText()+"\n");
         System.out.println(jFormattedTextDateTaskBegin.getText()+"\n");
         System.out.println(jTextField1DayTaskEnd.getText()+"\n");
         System.out.println(jTextField3TimeStart.getText()+"\n");
         System.out.println(jTextField2TimeEnd.getText()+"\n");
         System.out.println(jTextField4Status.getText()+"\n");
         System.out.println(jCheckBox1AllDay.getText()+"\n");
         
    }//GEN-LAST:event_jButton2CommitAddtaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaToDoAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaToDoAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaToDoAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaToDoAppGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaToDoAppGui().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton2AddTask;
    private javax.swing.JButton jButton2CommitAddtask;
    private javax.swing.JButton jButton2Logout;
    private javax.swing.JCheckBox jCheckBox1AllDay;
    private javax.swing.JDialog jDialog1TaskModyf;
    private javax.swing.JFormattedTextField jFormattedTextDateTaskBegin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Msg;
    private javax.swing.JLabel jLabel1MsgContent;
    private javax.swing.JLabel jLabel1TextLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2TextPass;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1UserPass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1TaskViews;
    private javax.swing.JTextArea jTextArea1DescriptionTask;
    private javax.swing.JTextField jTextField1DayTaskEnd;
    private javax.swing.JTextField jTextField1TitleTask;
    private javax.swing.JTextField jTextField1User;
    private javax.swing.JTextField jTextField2TimeEnd;
    private javax.swing.JTextField jTextField3TimeStart;
    private javax.swing.JTextField jTextField4Status;
    // End of variables declaration//GEN-END:variables
}
